# Site settings
title: "Nuri Chang"
description: > 
  My writings

author: Nuri Chang
email: nuri.chang.1@gmail.com
twitter_username: TBD
github_username: TBD

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://deadbeef.me" # the base hostname & protocol for your site

google_analytics_id: TBD
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

